name: 0.0.$(Build.BuildId)

# Linux based agent; all except the first step will also work on Windows
pool:
  vmImage: ubuntu-latest

# The scheduled trigger will be set in the Azure DevOps portal
trigger: none

# Reference for the repository of the template file 
resources:
  repositories:
    - repository: ACMECertificateAutomation
      type: git
      name: ACME/ACMECertificateAutomation

steps:
- template: create_and_store_certificates.yml@ACMECertificateAutomation
  parameters:
    azureSubscription: '<YOUR-SERVICE-CONNECTION>'
    certs:
    - www.example.org
    
